---
title: "EDA with R Commander"
author: "Melinda Higgins"
date: "January 31, 2017"
---


```{r echo=FALSE, message=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```


```{r echo=FALSE}
# include this code chunk as-is to enable 3D graphs
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```

Add R code to load the cmc dataset

```{r}
# R Script for loading the cmc dataset
# and loading the Rcmdr package and 
# starting the Rcmdr GUI interface

# load the cmc dataset into the local environment
load("cmc.RData")

# load the Rcmdr package 
# this also starts the Rcmdr GUI interface
library(Rcmdr)
```


```{r}
summary(cmc)
```


```{r}
library(abind, pos=22)
```


```{r}
library(e1071, pos=23)
```


```{r}
tb <- numSummary(cmc[,c("NumChild", "WifeAge")], statistics=c("mean", "sd", "IQR",
   "quantiles"), quantiles=c(0,.25,.5,.75,1))

# pull the $table out of the numSummary() output which is a list
# then use knitr::kable() to make a prettier table
knitr::kable(numSummary(cmc[,c("NumChild", "WifeAge")], statistics=c("mean", "sd", "IQR",
   "quantiles"), quantiles=c(0,.25,.5,.75,1))$table)

```

```{r}
# pipe the $table into knitr::kable()
# make sure dplyr package is loaded so the %>% will work
library(dplyr)
numSummary(cmc[,"NumChild"], groups=cmc$Contraceptive, statistics=c("mean", 
  "sd", "IQR", "quantiles"), quantiles=c(0,.25,.5,.75,1))$table %>%
  knitr::kable()
```

```{r}
local({
  .Table <- with(cmc, table(Contraceptive))
  cat("\ncounts:\n")
  print(.Table)
  # add knitr::kable() to improve .Tabe output
  # convert to a data.frame first
  knitr::kable(as.data.frame(.Table))
  cat("\npercentages:\n")
  print(round(100*.Table/sum(.Table), 2))
  # convert to a data.frame THEN pipe to knitr::kable() and
  # update the column names
  as.data.frame(round(100*.Table/sum(.Table), 2)) %>% 
    knitr::kable(col.names = c("Contraceptive","Percentages"))
})

# NOTE - only the 2nd knitr::kable() table
# shows up in the Rmarkdown - since the code
# above is inside the local() environment...

local({
  .Table <- with(cmc, table(HusbOcc))
  cat("\ncounts:\n")
  print(.Table)
  cat("\npercentages:\n")
  print(round(100*.Table/sum(.Table), 2))
})
```

```{r}
with(cmc, tapply(NumChild, list(Contraceptive), median, na.rm=TRUE))
```

```{r}
library(nortest, pos=24)
```


```{r}
with(cmc, shapiro.test(NumChild))
```

```{r}
local({
  .Table <- xtabs(~Contraceptive+HusbOcc, data=cmc)
  cat("\nFrequency table:\n")
  print(.Table)
  cat("\nColumn percentages:\n")
  print(colPercents(.Table))
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
```

```{r}
t.test(NumChild~WifeRel, alternative='two.sided', conf.level=.95, 
  var.equal=FALSE, data=cmc)
```

```{r}
library(mvtnorm, pos=25)
```


```{r}
library(survival, pos=25)
```


```{r}
library(MASS, pos=25)
```


```{r}
library(TH.data, pos=25)
```


```{r}
library(multcomp, pos=25)
```


```{r}
AnovaModel.1 <- aov(NumChild ~ WifeEd, data=cmc)
summary(AnovaModel.1)
with(cmc, numSummary(NumChild, groups=WifeEd, statistics=c("mean", "sd")))
```

```{r}
scatterplot(NumChild~WifeAge, reg.line=FALSE, smooth=TRUE, spread=FALSE, 
  boxplots=FALSE, span=0.5, ellipse=FALSE, levels=c(.5, .9), data=cmc)
```

```{r}
Boxplot(NumChild~WifeEd, data=cmc, id.method="y")
```

